<?php
/**
 * Created by PhpStorm.
 * User: isuru
 * Date: 10/27/17
 * Time: 2:11 AM
 */

namespace Isuru\ApiClient;

require_once __DIR__ . '/../vendor/autoload.php';

class SimpleOwmClientTest extends \PHPUnit\Framework\TestCase
{

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->sowmc = new SimpleOwmClient('Colombo, Sri Lanka', '');
    }

    public function testIsValidCity() {
        return $this->assertEquals($this->sowmc->cityName, 'Colombo, Sri Lanka');
    }

}
